package constants

const (
    APP_INDEX = "app"
    USER_INDEX = "user"
    ES_URL = "YOUR ELASTICSEARCH URL"
    ES_USERNAME = "YOUR ELASTICSEARCH USERNAME"
    ES_PASSWORD = "YOUR ELASTICSEARCH PASSWORD"
    STRIPE_API_KEY = "YOUR STRIPE API KEY"
    GCS_BUCKET = "YOUR GOOGLE CLOUD STORAGE BUCKET"
)
